### ISSUE TITLE
Cannot get the localization result from the controller

### ISSUE THREAD

**Issue by dkoung** [SICKAG/sick_lidar_localization#12]
Hello,

I have SIM Localization controller running with two nanoScan3. I can see the localization on SOPASair, but I could not get the result via ROS.

I'm running ROS Melodic.

Edit: I can also call some services successfully such as /LocStop, /LocStartLocalizing, and /LocRequestTimestamp, while some other return false.

**Comment by rostest** [comment]
Thanks for reporting. Can you give some more information, logfiles or messages from the sick_lidar_localization process? If you start sick_lidar_localization with option `verbose:=1` in a shell, informational and possible error messages are printed, e.g.
```
roslaunch sick_lidar_localization sick_lidar_localization.launch verbose:=1
```

A logfile or a screenshot of the sick_lidar_localization messages would be very helpfull.

To receive result messages from the SIM localization controller, both the IP address of the SIM (i.e. the UDP sender) and the IP adress of your local PC (i.e. the UDP receiver of result telegrams) have to be configured. You can do this either in the launch-file:
```
  <arg name="hostname"   default="192.168.0.1"/>         <!-- IP adress of the localization controller --> 
  <arg name="udp_ip_sim_output" default=""/>             <!-- IP address for output UDP messages, or "" for broadcast (INADDR_ANY), default: "", use IP address of your local machine --> 
  <arg name="udp_ip_sim_input" default="192.168.0.1"/>   <!-- IP address for input UDP messages, or "" for broadcast, default: "192.168.0.1", (IP adress of the localization controller) --> 
```
or by commandline, see https://github.com/SICKAG/sick_lidar_localization#options-and-configuration 

An example call is:
```
roslaunch sick_lidar_localization sick_lidar_localization.launch hostname:=192.168.0.1 udp_ip_sim_input:=192.168.0.1 udp_ip_sim_output:=<IP of your PC> verbose:=1
```

**Comment by dkoung** [comment]
Hello,

Thanks for your reply. The issue is solved; The problem was that the SIM controller was running an older version (LLS-1.5.1). I just updated it to version 2.1, and everything is fine.

**Comment by rostest** [comment]
Thanks for your message.

**Comment by Huyhust13** [comment]
Hi @rostest @dkoung 

I am facing the same problem. 
I run LLS-2.0 in window computer with ip 192.168.0.102. Run sick_lidar_localization package for ros 1 in computer ip 192.168.0.123. 
Run roslaunch with config: 
hostname:=192.168.0.102
udp_ip_sim_input:=192.168.0.102
udp_ip_sim_output:=192.168.0.123
verbose:=1
But i see nothing in those topic: 
![image](https://user-images.githubusercontent.com/34271857/147719725-28fe8e41-9828-4bfe-9db3-54de5623b748.png)

Thank you in advance!

**Comment by Huyhust13** [comment]
@rostest dear,

I updated my LidarLOC to version 2.1.0.9, but I still have nothing when subscribe to topic: `/localizationcontroller/out/localizatinocontroller_result_message_0502`

Please help me!

**Comment by Huyhust13** [comment]
Update...
I fixed my issue. It cause the mistake in configuration of LidarLOC.
