### ISSUE TITLE
Error installing LLS on Ubuntu 20.04 and ROS Noetic (duration.h tag 0.7.3)

### ISSUE THREAD

**Issue by DatZ2H** [SICKAG/sick_lidar_localization#16]
Hi Team,
When installing sick_lidar_localization Tag V5.5.2 on Ros Noetic Ubuntu 20.04, I'm encountering a conflict error.
![image](https://github.com/SICKAG/sick_lidar_localization/assets/52695336/33c65eff-e3cd-43c0-b2d3-7ee72c66996f)
I have observed that with the recent update of Ros Noetic, rostime/include/ros/duration.h tag 0.7.3 is conflicting with sick_lidar_localization. This issue doesn't occur with version 0.7.2.
The temporary action is to comment out lines 80 and 81 in the file located at /home/adlink/DatDQ/DatWS/src/sick_lidar_localization/include/sick_lidar_localization/sick_ros_wrapper.h.
![image](https://github.com/SICKAG/sick_lidar_localization/assets/52695336/5f44d61a-185e-436e-b873-eb39548c64b2)

**Comment by aozrobutel** [comment]
I have same issue :

![ss_error](https://github.com/SICKAG/sick_lidar_localization/assets/144930286/64d737aa-475b-4f47-b6c6-021f2ed29610)

**Comment by DatZ2H** [comment]
> I have same issue :
> 
> ![ss_error](https://user-images.githubusercontent.com/144930286/278675107-64d737aa-475b-4f47-b6c6-021f2ed29610.png)

You can follow this video https://youtu.be/OCiexTEN_G0?si=-pN-SocIBCV7VDQG

**Comment by aozrobutel** [comment]
> > I have same issue :
> > ![ss_error](https://user-images.githubusercontent.com/144930286/278675107-64d737aa-475b-4f47-b6c6-021f2ed29610.png)
> 
> You can follow this video https://youtu.be/OCiexTEN_G0?si=-pN-SocIBCV7VDQG

Thanks, problem solved
