### ISSUE TITLE
Lose Localization Problem for Sick Map Engineering Tool

### ISSUE THREAD

**Issue by sofohuwin** [SICKAG/sick_lidar_localization#17]
Hello Sick AG Team,
I work in GPM, Taiwan. We have the self-R&D AGV/AMR Ability. Our AGV is named "Parts AGV". 
We buy your hardware product: Sick Nano Scan3, Sick SIM1000, software product: Sick Map Engineering Tool and the LiDAR LOC Licence.
There are more vehicles running in the some of the semiconductor industry company client sides, 
but there are possibly the environment diversification, happen about lose localization problem for Sick Map Engineering Tool.

I have been searched your Sick AG patent. Discover your LiDAR LOC and Sick Map Engineering Tool, and use the algorithm: ICP and Extended Kalman Filter, EKF. 

If our vehicle is happen about lose localization problem for Sick Map Engineering Tool at the some time.
How should I adjust the any parameter to improve the localization rate ?

**Comment by tbohnma** [comment]
Hello, 

thanks for your detailed question and your interest in our algorithm. 

understandably, we cannot share parameter information in this open forum. 

As you probably know, we are already in close contact with your colleagues in the Support Portal about the specific problem you perceived. 

There, we can also provide specific parameter sets for your purpose!
