### ISSUE TITLE
No localization message published

### ISSUE THREAD

**Issue by whm210806** [SICKAG/sick_lidar_localization#22]
Hi, I'm using the picoscan150 loc for localization. After I launch the launch file, I can see the topics' names but no messages are streaming. The output of the launch file is attached to this message. What can I do to solve this problem?

Thank you.
![sick_localization_issue](https://github.com/user-attachments/assets/117f5834-6700-4f07-8e8b-210d85682825)

**Comment by riverne02** [comment]
Hello, 

There are multiple reason as to why this could be. 
Please ensure that the you the following requierements are met: 

1. Make sure the the device IP is correctly assgned. 
This is the IP address where the ROS driver will be runnning. 
These settings are under: 
**_SOPASAir > CONFIGURATION > Communication > output_**


![driver](https://github.com/user-attachments/assets/a59ab38d-e434-4018-9898-558894d72676)



2. Make sure that you are localized in an existing map. 
This is done in SOPASAir, and both of the Localization and Map Matching have a green icon. 

![loc](https://github.com/user-attachments/assets/c07366f9-d8d2-4e7c-87d9-c235d238fc98)


3. Make sure that the sick lidar localization launch file is correctly configure. 
Here is an example on how it should be configured

![launch](https://github.com/user-attachments/assets/5ca287e6-ab52-4354-bc6d-311a4f74bf60)

If the issue continues, then you are most likely trying to get the scan data to run on the /scan topic and also LiDAr-LOC.
If this is the case, then you will have to modify the configuration of the sick_scan_xd driver and the configuration of the picoscan. 

We have a tutorial that shows how to do this on the SICK Support portal. 
This tutorial is called "SICK Scanners for Multiple receivers and LiDAR-LOC".
We recommend that if the issue continues, create a ticket on our official support portal so we can help you further. 

https://support.sick.com/dashboard/ 

Best regards.
-Neftali

**Comment by whm210806** [comment]
Hi Neftali,

Thanks for your answer. The problem is solved by changing the configuration. I have a further question is that, I see there's a service to record sensor data, I want to know where the recorded data is saved, so that I can download it for mapping?

Thank you.
