### ISSUE TITLE
ROS 1 and ROS 2 distributions

### ISSUE THREAD

**Issue by tbohnma** [SICKAG/sick_lidar_localization#5]
Hello, 

which ROS distributions are tested and supported for each ROS 1 and ROS 2?

For ROS 1, I found melodic was tested: 
![image](https://user-images.githubusercontent.com/33319087/107005979-c69c0f80-6790-11eb-9226-4bb5cb855d12.png)

For ROS 2 I could find nothing. Is the current version https://index.ros.org/doc/ros2/Releases/Release-Foxy-Fitzroy/ supported?

Many thanks

**Comment by michael1309** [comment]
sick_lidar_localization supports ROS1 and ROS2 and has been tested with ROS1 melodic and ROS2 eloquent on Ubuntu 18.04. 

Make sure to build with ros2-package and cmake-flag ROS_VERSION=2 on ROS2:

https://github.com/SICKAG/sick_lidar_localization#install-and-build-on-ros2
https://github.com/SICKAG/sick_lidar_localization#run-on-ros2

  
![t0](https://user-images.githubusercontent.com/33296049/107120867-b28b0780-688f-11eb-80e8-4428414bc97e.png)
![t1](https://user-images.githubusercontent.com/33296049/107120881-b6b72500-688f-11eb-8382-6fd1a84a180d.png)



 


 

sick_lidar_localization has been tested successfully with ROS2 Eloquent on Ubuntu 18.04. We do not expect issues on ROS2 Foxy, but recommend tests before usage in a productive environment.

**Comment by tbohnma** [comment]
Thanks for the clarification
