### ISSUE TITLE
Wrong service name

### ISSUE THREAD

**Issue by Edwin123456789** [SICKAG/sick_lidar_localization#6]
Hi,

The following comment has one time too much ' sick' in it. It should be ' SickLocSetPoseSrv'  and not '**Sick**SickLocSetPoseSrv' 

ros2 service call SickLocSetPose sick_lidar_localization/srv/SickSickLocSetPoseSrv "{posex: 10300, posey: -5200, yaw: 30000, uncertainty: 1000}" # expected answer: "success: True" # Initialize vehicle pose

This was also the case with some other services

Though, the service itself works fine :)

**Comment by rostest** [comment]
@Edwin123456789 Thanks for your friendly feedback! The examples in Readme.md are now updated.
