### ISSUE TITLE
How to get the SIM data and nanoScan3 laser scan at the same time

### ISSUE THREAD

**Issue by guangjhaogu** [SICKAG/sick_lidar_localization#8]
HI, I use ROS for my AGV,and install sick_lidar_localization and sick_safetyscanner from github. So I need both SIM result data and laser scan data at the same time. But when I run both of them, the cahannel will stuck. Is there any solution to slove this problem, thanks.

**Comment by tbohnma** [comment]
Hello @guangjhaogu, 
sorry for the late reply. Contrary, to the statement above, a parallel usage is of course possible. 

You would have to use the broadcast setting for the safety sensor as described in the Technical Information - Hardware Integration:
- https://supportportal.sick.com/Product_notes/lidar-loc-hardware-integration/

See also the 2 other issues discussing this topic: 
- https://github.com/SICKAG/sick_safetyscanners/issues/27
- https://github.com/SICKAG/sick_safetyscanners/issues/74

**Comment by rostest** [comment]
Closed due to inactivity.

**Comment by nguyendo1403** [comment]
Hi @tbohnma!
I'm using Sick Microscan3 and ROS IPC. I want to use lidar for Lidar-loc and run package ROS sick_safetyscanner.
But, when I run MS3 with Lidar-loc first. It's OK.
Then, I run package Sick_microscan3 =>Error: Lidar-loc can't get data from lidar.

My configuration:
MS3:
- ip:192.168.3.4
- ip address: 192.168.3.100
- UDP port: 6060

ROS IPC:
- ip:192.168.3.100
Please, refer to the attached pptx for more detailled description. Thank you very much! 
[](u
[LiDAR-LOC_ROS.pptx](https://github.com/SICKAG/sick_lidar_localization/files/12733917/LiDAR-LOC_ROS.pptx)
rl)

**Comment by pablo-sick** [comment]
Dear @nguyendo1403 ,

It's Pablo Abia, application engineer from LiDAR-LOC. I could reproduce the same issue on my PC. As you say, with your current configuration it does not seem possible to get the data on both LiDAR-LOC and the sick_safetyscanners ros driver... 

I also tried setting up the sensor to broadcast the output data (in Safety Designer, by configuring the target IP as xxx.xxx.xxx.255), but I came up with the same issue.

One possible solution is to use a script to forward the traffic on 192.168.3.100:6060 to another port like 192.168.3.100:6061 and then configuring LiDAR-LOC to listen to one of them, and the sick_safetyscanners ros driver to listen to the other. On Github you can find some python scripts that performs this operation, like this one from the link below:

**Comment by nguyendo1403** [comment]
Hi  Pablo Abia,

By the way, let me ask how to switch monitoring case of Sick microscan3
when i run ROS package sick_safetyscanners.
I have configured with 2 monitoring cases for sick microscan3 on Safety
Designer

Nguyen,

Vào Th 6, 29 thg 9, 2023 vào lúc 23:39 pablo-sick <
***@***.***> đã viết:

**Comment by pablo-sick** [comment]
Dear @nguyendo1403 , I forwarded this question to the sick_safetyscanners repository, since they can better answer your question than me.

Best regards,

Pablo

**Comment by tbohnma** [comment]
Hello @nguyendo1403,
It seems you raised the question about monitoring cases in several issues. Please use the already provided answer in https://github.com/SICKAG/sick_safetyscanners/issues/137

Thanks!
